name = "PlutoVTKPlot"
uuid = "19f70b67-2887-4cf9-b19e-fe1a30c34d85"
authors = ["Juergen Fuhrmann <juergen.fuhrmann@wias-berlin.de>"]
version = "0.0.3"

[deps]
ColorSchemes = "35d6a980-a343-548e-a6ea-1d62b119f2f4"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
PlutoCanvasPlot = "57876ffe-7b7d-4c51-befe-9eb7dc4baaca"

[compat]
ColorSchemes = "3"
Colors = "0.12"
PlutoCanvasPlot = "0.0.5"
julia = "1.5"
